### ISSUE TITLE
Unable to run/install modules.image

### ISSUE THREAD

**Issue by nidens** [bannsec/stegoVeritas#1]
When attempting to run stegoVeritas.py I am consistently receiving this error. Is this normal? I've installed all dependencies. 

```
Type:	Windows Bitmap
Mode:	RGB

Traceback (most recent call last):
  File "stegoveritas.py", line 69, in <module>
    import modules.image
ImportError: No module named 'modules.image'; 'modules' is not a package
```

in the ~/stegoVeritas/modules folder should an ```__init.py__``` be placed?

**Comment by Owlz** [comment]
Oops... Yeah, sorry this isn't a proper package atm.

```bash
$ export PATH=$PATH:/path/to/stegoVeritas/root
```

Going to keep this open as a reminder that I need to actually make this pip installable, which would take care of that.

**Comment by huanglitong123** [comment]
When attempting to run stegoVeritas.py I am consistently receiving this error. Is this normal? I've installed all dependencies
OS:WINDOWS 7 x64
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (In
tel)] on win32
F:\steganography\stegoVeritas-master>python3 stegoveritas.py "miao~870F6C667A6CD
C0D1F533859E72C48E0.jpg"
Type:   JPEG (ISO 10918)
Mode:   RGB

Checking Meta Data

Exif Data
=========
Image XResolution:      144
Image YCbCrPositioning: Centered
Image Artist:   key:m1a0@888
Image ResolutionUnit:   Pixels/Inch
Image YResolution:      144


Checking for trailing data
Running image filters
Attempting to brute force LSB items
Trying 0.0.0
Traceback (most recent call last):
  File "stegoveritas.py", line 70, in <module>
    modules.image.run(fArray,args)
  File "F:\steganography\stegoVeritas-master\modules\image\__init__.py", line 98
, in run
    autoAnalysis(f,args)
  File "F:\steganography\stegoVeritas-master\modules\image\__init__.py", line 37
, in autoAnalysis
    modules.image.imageLSB.auto(f,args)
  File "F:\steganography\stegoVeritas-master\modules\image\imageLSB.py", line 12
7, in auto
    testOutput(o,args)
  File "F:\steganography\stegoVeritas-master\modules\image\imageLSB.py", line 25
, in testOutput
    out = subprocess.check_output(["file",TEMPFILE])
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\subprocess.
py", line 626, in check_output
    **kwargs).stdout
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\subprocess.
py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\subprocess.
py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\subprocess.
py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system can not find the file 。

Thank you.

**Comment by Owlz** [comment]
Ah. Yeah. So I need to change my file dependency over to a python based one. Opening a new issue.

**Comment by bannsec** [comment]
Well, this has lingered.. Anyway, there's an entirely refactored version of this that should alleviate this issue.

```bash
$ pip3 install stegoveritas
$ stegoveritas_install_deps
```

or

```bash
$ sudo docker run -it --rm bannsec/stegoveritas
```

If this is still an issue, feel free to re-open :-)
