### ISSUE TITLE
stegoveritas-binwalk

### ISSUE THREAD

**Issue by noraj** [bannsec/stegoVeritas#15]
1. What is the difference between [stegoveritas-binwalk](https://pypi.org/project/stegoveritas-binwalk/) and [binwalk](https://pypi.org/project/binwalk/).
2. If they are the same, why a new python package?
3. IF they are different, why there is not a git repository of the patch applied to transform binwalk into stegoveritas-binwalk?

**Comment by bannsec** [comment]
Basically, the `binwalk` package in pypi was last updated January 2015. Also, the binwalk primary dev mentioned even back then that it wasn't pushed to pypi by him nor is he maintaining it (https://github.com/ReFirmLabs/binwalk/issues/121#issuecomment-244626235). Zach Riggle pushed it and obviously he isn't bothering to maintain it either.

For stegoVeritas, i wanted it to be able to install needed deps via pypi, thus I've pushed my own version. Functionally, it's the same as the github master, with the only tweaks I made to enable it to package and (hopefully) install correctly.

Unfortunately, the way pypi works and the current environment for binwalk, it's unlikely that the binwalk dev/s will desire or be able to update the base binwalk package.
