### ISSUE TITLE
platform.dist() deprecation

### ISSUE THREAD

**Issue by noraj** [bannsec/stegoVeritas#19]
About `install_deps.py`

```python
>>> platform.dist()
__main__:1: DeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5
```

Similar issue and fix: https://github.com/saltstack/salt/issues/37070

According to https://bugs.python.org/issue1322, it will be removed in python 3.8.

**Comment by bannsec** [comment]
Thanks for the heads up. Looks like we'll need to replace those calls with the `distro` package:

https://pypi.org/project/distro/
