### ISSUE TITLE
parrot testing

### ISSUE THREAD

**Issue by bannsec** [bannsec/stegoVeritas#38]
Right now parrot is having ridiculous mirror issues so testing is not possible. If they ever fix their crap I'll have to re-add.

**Comment by greybeard-code** [comment]
Distributor ID:	Parrot
Description:	Parrot OS 5.1 (Electro Ara)
Release:	5.1
Codename:	ara
  
```
$stegoveritas_install_deps
Unhandled distribution to install deps: parrot os
Please poke me or submit a PR.
```

**Comment by bannsec** [comment]
Finally got a chance to work on this. It's working again (lsb/dependency installs/tests/etc). #41 

Will push this in next release.
